/**
 * OAuth callback route — no longer used.
 *
 * CoFound now uses the `claude setup-token` approach:
 * users paste a 1-year OAuth bearer token generated by the Claude Code CLI.
 * No OAuth app registration or callback handling is needed.
 *
 * See: src/app/login/page.tsx and src/app/api/auth/login/route.ts
 */

import { NextResponse } from "next/server";

export async function GET() {
  return NextResponse.redirect("/login");
}
